//
// Created by marvin on 4/19/23.
//

#ifndef MASTER_IMAGE_CONSTRUCTOR_HALO12_VA41630_KRYPTON_SILVER_BOEING_HARDWARECONTROL_HARDWARE_CONTROL_H_
#define MASTER_IMAGE_CONSTRUCTOR_HALO12_VA41630_KRYPTON_SILVER_BOEING_HARDWARECONTROL_HARDWARE_CONTROL_H_
//Start me
void hwc_main(void *pv);
void hwc_init(void);

#endif //MASTER_IMAGE_CONSTRUCTOR_HALO12_VA41630_KRYPTON_SILVER_BOEING_HARDWARECONTROL_HARDWARE_CONTROL_H_
