//
// Created by marvin on 5/5/23.
//

#ifndef CHECKOUT_SH_EXODRIVERS_DRIVERS_VA41630_RTOS_SERIAL_DRIVER_SERIAL_VA41630_RTOS_H_
#define CHECKOUT_SH_EXODRIVERS_DRIVERS_VA41630_RTOS_SERIAL_DRIVER_SERIAL_VA41630_RTOS_H_
#include "serial/hal_serial.h"

#define UART_NUM 3

int serial_channel_init(const uart_init_t *ui);
#endif //CHECKOUT_SH_EXODRIVERS_DRIVERS_VA41630_RTOS_SERIAL_DRIVER_SERIAL_VA41630_RTOS_H_
