//
// Created by marvin on 2/8/23.
//

#ifndef MASTER_IMAGE_CONSTRUCTOR_HALO12_VA41630_KRYPTON_SILVER_BOEING_THRUSTER_CONTROL_PROJECT_HALO12_VA41630_PROJECT_SHARED_INCLUDE_TASK_PRIORITY_H_
#define MASTER_IMAGE_CONSTRUCTOR_HALO12_VA41630_KRYPTON_SILVER_BOEING_THRUSTER_CONTROL_PROJECT_HALO12_VA41630_PROJECT_SHARED_INCLUDE_TASK_PRIORITY_H_
#include "FreeRTOS.h"

#define UART_RX_TASK_PRIO      (configMAX_PRIORITIES - 1)
#define UART_TX_TASK_PRIO      (configMAX_PRIORITIES - 1)
#define MSG_HANDLER_TASK_PRIO  (configMAX_PRIORITIES - 3)
#define INTER_COMM_TASK_PRIO   (configMAX_PRIORITIES - 4)
#define CANOPEN_TASK_PRIO      (tskIDLE_PRIORITY)
#define TRACE_TASK_PRIO        (tskIDLE_PRIORITY)

#endif//MASTER_IMAGE_CONSTRUCTOR_HALO12_VA41630_KRYPTON_SILVER_BOEING_THRUSTER_CONTROL_PROJECT_HALO12_VA41630_PROJECT_SHARED_INCLUDE_TASK_PRIORITY_H_
